export const DUMMY_PRODUCT = [
  {
    id: 1,
    title:
      "Adidas black t-shirt lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    category: "Men",
    img: "images/main-img.PNG",
    price: 9.999,
    quantity: 1,
    rate: "4.9",
    "rate-count": 22,
    disscount: 30,
    size: ["small", "Medium", "Large", "X Large", "XX Large"],
  },
  {
    id: 2,
    title: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    category: "Woman",
    img: "images/Group 575.png",
    price: 9.999,
    quantity: 1,
    rate: "4.2",
    "rate-count": 22,
    disscount: 50,
    size: ["small", "Medium", "Large", "X Large", "XX Large"],
  },
  {
    id: 3,
    title: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    category: "Men",
    img: "images/Group 583.png",
    price: 9.999,
    quantity: 1,
    rate: "4.2",
    "rate-count": 22,
    size: ["small", "Medium", "Large", "X Large", "XX Large"],
  },
  {
    id: 4,
    title: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    category: "Men",
    img: "images/Group 589.png",
    price: 9.999,
    quantity: 1,
    rate: "4.2",
    "rate-count": 22,
    disscount: 30,
    size: ["small", "Medium", "Large", "X Large", "XX Large"],
  },
  {
    id: 5,
    title: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    category: "Men",
    img: "images/Group 597.png",
    price: 9.999,
    quantity: 1,
    rate: "4.2",
    "rate-count": 22,
    disscount: 70,
    size: ["small", "Medium", "Large", "X Large", "XX Large"],
  },
  {
    id: 6,
    title: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    category: "Woman",
    img: "images/Group 575.png",
    price: 700,
    quantity: 1,
    rate: "4.2",
    "rate-count": 22,
    disscount: 50,
    size: ["small", "Medium", "Large", "X Large", "XX Large"],
  },
  {
    id: 7,
    title: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    category: "Men",
    img: "images/Group 583.png",
    price: 9.999,
    quantity: 1,
    rate: "4.2",
    "rate-count": 22,
    size: ["small", "Medium", "Large", "X Large", "XX Large"],
  },
  {
    id: 8,
    title: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    category: "Men",
    img: "images/Group 589.png",
    price: 9.999,
    quantity: 1,
    rate: "4.2",
    "rate-count": 22,
    disscount: 30,
    size: ["small", "Medium", "Large", "X Large", "XX Large"],
  },
  {
    id: 9,
    title: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    category: "Men",
    img: "images/Group 597.png",
    price: 9.999,
    quantity: 1,
    rate: "4.2",
    "rate-count": 22,
    disscount: 70,
    size: ["small", "Medium", "Large", "X Large", "XX Large"],
  },
];
